# Generated by Django 2.2.7 on 2019-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlShortener",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField(verbose_name="Long URL", db_index=True,)),
                ("short_url", models.URLField(blank=True, verbose_name="Short URL")),
                (
                    "url_short_code",
                    models.SlugField(
                        unique=True, db_index=True, verbose_name="URL Short Code"
                    ),
                ),
            ],
            options={
                "verbose_name": "URL Shortener",
                "verbose_name_plural": "URL Shortener",
            },
        ),
    ]
